### ISSUE TITLE
ServiceBus FIFO guarantee 

### ISSUE THREAD

**Issue by kolipka** [FoundatioFx/Foundatio.AzureServiceBus#7]
as stated in docs: https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-sessions
`To realize a FIFO guarantee in Service Bus, use Sessions`

Similar problem with FIFO guarantee apply to [Storage Queue](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-azure-and-service-bus-queues-compared-contrasted#additional-information)
`Messages in Storage queues are typically first-in-first-out, but sometimes they can be out of order; for example, when a message's visibility timeout duration expires (for example, as a result of a client application crashing during processing)`

Are there any plans to support Sessions in Foundatio?

**Comment by niemyjski** [comment]
We'd be willing to accept a pr for this. We could add an option for this and support both current and ordered messages.
